packageExtensions:
  "@mantine/core@*":
    peerDependencies:
      "@emotion/react": "*"
  "@mantine/next@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/server": "*"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
