name: Build project
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    name: Build for Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Windows
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: Game
      - uses: actions/upload-artifact@v2
        with:
          name: Build-Windows
          path: build/StandaloneWindows64
          retention-days: 3
