name: Check Format
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  format:
    name: Format check by csharpier 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: install csharpier
        run: dotnet tool install -g csharpier
      - name: check format
        run: dotnet csharpier --check .
