name: Build project
on:
  push:
  pull_request:
  workflow_dispatch: {}
jobs:
  format:
    name: Format check by csharpier 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: install csharpier
        run: dotnet tool install -g csharpier
      - name: check format
        run: dotnet csharpier --check .
  build:
    name: Build for Windows
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Windows
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: Game
      - uses: actions/upload-artifact@v2
        with:
          name: Build-Windows
          path: build/StandaloneWindows64
          retention-days: 3
